nohup sh run_main.sh \
      --model output/models/GLProtein/encoder \
      --output_file fluorescence-GLProtein \
      --task_name fluorescence \
      --do_train True \
      --epoch 15 \
      --mean_output True \
      --optimizer Adam \
      --per_device_batch_size 4 \
      --gradient_accumulation_steps 16 \
      --eval_step 50 \
      --eval_batchsize 32 \
      --warmup_ratio 0.0 \
      --learning_rate 1e-3 \
      --seed 3 \
      --frozen_bert True > output/fluorescence/GLProtein.out 2>&1
